// <auto-generated />
using System;
using KiteFlow.Services.Equipment.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KiteFlow.Services.Equipment.Api.Migrations
{
    [DbContext(typeof(EquipmentDbContext))]
    [Migration("20260313152830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.EquipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentCondition")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastServiceDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastServiceUsageMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("SizeLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalUsageMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.HasIndex("SchoolId", "TagCode");

                    b.HasIndex("SchoolId", "Type");

                    b.ToTable("equipment_items", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.EquipmentUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CheckoutItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsageMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SchoolId", "EquipmentId", "RecordedAtUtc");

                    b.ToTable("equipment_usage_logs", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.GearStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name")
                        .IsUnique();

                    b.ToTable("gear_storages", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.LessonEquipmentCheckout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckedInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedInByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedOutAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotesAfter")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NotesBefore")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "LessonId")
                        .IsUnique();

                    b.ToTable("lesson_equipment_checkouts", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.LessonEquipmentCheckoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CheckoutId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ConditionAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ConditionBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotesAfter")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotesBefore")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SchoolId", "CheckoutId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("lesson_equipment_checkout_items", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ServiceDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageMinutesAtService")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SchoolId", "ServiceDateUtc");

                    b.ToTable("maintenance_records", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.MaintenanceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ServiceEveryDays")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceEveryMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "EquipmentType")
                        .IsUnique();

                    b.ToTable("maintenance_rules", (string)null);
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.EquipmentItem", b =>
                {
                    b.HasOne("KiteFlow.Services.Equipment.Api.Domain.GearStorage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.EquipmentUsageLog", b =>
                {
                    b.HasOne("KiteFlow.Services.Equipment.Api.Domain.EquipmentItem", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.LessonEquipmentCheckoutItem", b =>
                {
                    b.HasOne("KiteFlow.Services.Equipment.Api.Domain.LessonEquipmentCheckout", "Checkout")
                        .WithMany()
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiteFlow.Services.Equipment.Api.Domain.EquipmentItem", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("KiteFlow.Services.Equipment.Api.Domain.MaintenanceRecord", b =>
                {
                    b.HasOne("KiteFlow.Services.Equipment.Api.Domain.EquipmentItem", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
