const labelMap: Record<string, string> = {
  Dashboard: "Painel",
  Command: "Comando",
  "Command Center": "Centro de comando",
  Students: "Alunos",
  Instructors: "Instrutores",
  Courses: "Cursos",
  Enrollments: "Matrículas",
  Lessons: "Agenda",
  Equipment: "Equipamentos",
  Maintenance: "Manutenção",
  Finance: "Financeiro",
  "School Admin": "Administração da escola",
  Owner: "Proprietário",
  Admin: "Administrativo",
  Instructor: "Instrutor",
  Student: "Aluno",
  SystemAdmin: "Administrador do sistema",
  Discovery: "Descoberta",
  Beginner: "Iniciante",
  Intermediate: "Intermediário",
  Advanced: "Avançado",
  Single: "Avulsa",
  Course: "Curso",
  Scheduled: "Agendada",
  Confirmed: "Confirmada",
  Realized: "Realizada",
  Rescheduled: "Remarcada",
  Cancelled: "Cancelada",
  CancelledByWind: "Cancelada por vento",
  NoShow: "Não compareceu",
  Active: "Ativo",
  Inactive: "Inativo",
  Suspended: "Inativa",
  Completed: "Concluída",
  InProgress: "Em andamento",
  Locked: "Aguardando etapa anterior",
  Expired: "Expirada",
  Pending: "Pendente",
  Accepted: "Aceito",
  Excellent: "Excelente",
  Good: "Boa",
  Attention: "Atenção",
  NeedsRepair: "Precisa de reparo",
  OutOfService: "Fora de serviço",
  Usage: "Uso",
  Date: "Data",
  Condition: "Condição",
  Open: "Aberto",
  PartiallyPaid: "Parcial",
  Paid: "Pago",
  DueSoon: "A vencer",
  Delinquent: "Inadimplente",
  UpToDate: "Em dia",
  Closed: "Fechado",
  "Medical Note": "Observação médica",
  "Portal Enabled": "Portal ativo",
  "Portal Pending": "Portal pendente",
  MustChangePassword: "Troca de senha",
  LessonRealized: "Aula realizada",
  LessonRefunded: "Saldo devolvido",
  Capability: "Capacidade",
  EnrollmentSale: "Venda de matrícula",
  SingleLesson: "Aula avulsa",
  ManualAdjustment: "Ajuste manual",
  LessonReminder: "Lembrete de aula",
  LessonScheduled: "Aula agendada",
  LessonRescheduled: "Aula remarcada",
  LessonCancelled: "Aula cancelada",
  PresenceConfirmed: "Presença confirmada",
  Operations: "Operação",
  Payroll: "Folha de pagamento",
  Logistics: "Logística",
  Marketing: "Marketing",
  Other: "Outros",
  Recebimento: "Recebimento"
};

export function translateLabel(value: string | null | undefined) {
  if (!value) {
    return "-";
  }

  return labelMap[value] ?? value;
}
